const GET_CART = "GET_CART";
const ADD_TO_CART = "ADD_TO_CART";
const DELETE_FROM_CART = "DELETE_FROM_CART";
const CART_LOADING = "CART_LOADING";
const UPDATE_CART = "UPDATE_CART";
const UPDATE_ADDRESS = "UPDATE_ADDRESS";

export {GET_CART, ADD_TO_CART, DELETE_FROM_CART, CART_LOADING, UPDATE_CART, UPDATE_ADDRESS};