const GET_CART = "GET_CART";
const ADD_TO_CART = "ADD_TO_CART";
const DELETE_FROM_CART = "DELETE_FROM_CART";
const CART_LOADING = "CART_LOADING";

export {GET_CART, ADD_TO_CART, DELETE_FROM_CART, CART_LOADING};